name: Publish Release

on:
  push:
    tags:
      - 'v*' # Si attiva solo quando invii un tag che inizia con "v" (es. v1.0.0.7)

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Serve il permesso per scrivere la release
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: latest.zip
          generate_release_notes: true # Genera in automatico una lista dei commit dal rilascio precedente
